apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
        - name: fe
          image: halntit/kub-demo-fe:latest