apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec:
  selector:
    app: fe
  type: LoadBalancer # can be accessed from outside
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80