apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  type: LoadBalancer # can be accessed from outside
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000